service: dynamoDB
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: Admin
  region: eu-north-1
  iam:
    role: arn:aws:iam::119763079540:role/test

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getUser:
    handler: functions/user/getUser/index.handler
    events:
      - httpApi:
        path: api/user
        method: GET
  newUser:
    handler: functions/user/newUser/index.handler
    events:
      - httpApi:
        path: api/user
        method: POST
  getPasses:
    handler: functions/pass/getPasses/index.handler
    events:
      - httpApi:
        path: api/pass
        method: GET
  newPass:
    handler: functions/pass/newPass/index.handler
    events:
      - httpApi:
        path: api/pass
        method: POST
  editPass:
    handler: functions/pass/editPass/index.handler
    events:
      - httpApi:
        path: api/pass/{id}
        method: PUT
  deletePass:
    handler: functions/pass/deletePass/index.handler
    events:
      - httpApi:
        path: api/pass/{id}
        method: DELETE
        

resources:
  Resources:
    lckdUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    lckdPasses:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: passes
        AttributeDefinitions:
          - AttributeName: passId
            AttributeType: S
          - AttributeName: ownerId
            AttributeType: S
        KeySchema:
          - AttributeName: passId
            KeyType: HASH
          - AttributeName: ownerId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST